# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20180709_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Type')),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'fab_cuisine_types',
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_cuisine_type', to='restaurants.CuisineType')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_cuisine', to='restaurants.Restaurant')),
            ],
            options={
                'db_table': 'fab_restaurant_cuisine_type',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.ManyToManyField(related_name='restaurant_cuisine', through='restaurants.RestaurantCuisine', to='restaurants.CuisineType'),
        ),
    ]
