# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20180713_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Rs amount')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/dishes')),
                ('order_count', models.IntegerField(default=0)),
                ('course', models.SmallIntegerField(choices=[(1, b'Starter'), (2, b'Main Course'), (3, b'Desert')], default=2, verbose_name='Course')),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.CuisineType')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurants.Restaurant')),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'fab_food',
                'verbose_name': 'fab_food',
                'verbose_name_plural': 'fab_foods',
            },
        ),
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
