# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20180724_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='course',
            field=models.SmallIntegerField(choices=[(1, b'Starter'), (2, b'Main Course'), (3, b'Desert'), (4, b'Other')], default=4, verbose_name='Course'),
        ),
    ]
