# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('profile_image', models.ImageField(upload_to='profile/user', verbose_name='Profile Image')),
                ('status', models.SmallIntegerField(choices=[(1, b'Pending'), (2, b'Approved'), (3, b'Rejected')], default=2, verbose_name='Status')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fab_user',
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profile',
            },
        ),
    ]
