# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180706_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/user', verbose_name='Profile Image'),
        ),
    ]
