# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180706_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
    ]
